In [3]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.9.0
False


## Creating tensor CPU example

In [4]:
import torch

first_tens = torch.tensor([[12,10,11,9], [13,15,14,16]])
second_tens = torch.tensor([[1,2,3,4], [5,6,7,8]])
add_tens = first_tens + second_tens
print(add_tens)
print(add_tens.size())
print(add_tens.ndimension())


tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])
2


In [5]:
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"
print(device)

cpu


In [ ]:
# # ----- Example 1: 1D -> 2D -----
# x = torch.arange(12)
# print("\nOriginal x:", x, "shape:", x.shape)

# y = x.view(3, 4)
# print("x.view(3, 4):\n", y, "shape:", y.shape)


Original x: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) shape: torch.Size([12])
x.view(3, 4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) shape: torch.Size([3, 4])


In [7]:
first_a = torch.tensor([[12,10,11,9], [13,15,14,16]], device=device) # tensor should be created on GPU # 2 dimensional tensor from python list
second_b = torch.tensor([[1,2,3,4], [5,6,7,8]], device=device)
multi_tens = first_a * second_b
print(multi_tens)

tensor([[ 12,  20,  33,  36],
        [ 65,  90,  98, 128]])


In [8]:
# # example of normal and unform distribution
# import torch
# import matplotlib.pyplot as plt

# # -----------------------------
# # 1. Generate random tensors
# # -----------------------------
# # Uniform distribution [0,1)
# uniform_tensor = torch.rand(10000)

# # Normal distribution (mean=0, std=1)
# normal_tensor = torch.randn(10000)

# # -----------------------------
# # 2. Plot histograms
# # -----------------------------
# plt.figure(figsize=(12, 5))

# # Uniform
# plt.subplot(1, 2, 1)
# plt.hist(uniform_tensor.numpy(), bins=30, edgecolor="black")
# plt.title("Uniform Distribution [0,1)")
# plt.xlabel("Value")
# plt.ylabel("Frequency")

# # Normal
# plt.subplot(1, 2, 2)
# plt.hist(normal_tensor.numpy(), bins=30, edgecolor="black")
# plt.title("Normal Distribution (mean=0, std=1)")
# plt.xlabel("Value")
# plt.ylabel("Frequency")

# plt.tight_layout()
# plt.show()



In [9]:
#  create tensor and splits into smaller tensors
import torch

# with only number 10
x = torch.full((8,5), 10)
y = torch.arange(16)
# print(x)
# print(y)

#create 4 chunkc in one dimensions
def split_x_chunks(x):
  return x.chunk(chunks=4, dim=0)

def split_x_customs(x):
  return x.split([5,3], dim=0) # first tensor will have 5 rows, 2nd will have 3 rows

#splits tensors in dimensions (5,3) into 1st dimensions

split_x_chunks(x)
split_x_customs(x)

(tensor([[10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10]]),
 tensor([[10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10]]))

In [10]:
# stack tensors
torch.stack((x, x))

tensor([[[10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10]],

        [[10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10],
         [10, 10, 10, 10, 10]]])

In [11]:
# splitting tensors
first, second = torch.unbind(first_tens)
print(first, second)

tensor([12, 10, 11,  9]) tensor([13, 15, 14, 16])


In [12]:
# mathematical-functions
a = torch.tensor([10,2,8,6,4])
b = torch.tensor([10,2,8,6,4])
print("adding", a.add(b))
print("mult", a.mul(b))
print("divid", a.div(b))


adding tensor([20,  4, 16, 12,  8])
mult tensor([100,   4,  64,  36,  16])
divid tensor([1., 1., 1., 1., 1.])


In [13]:
# reduction function
# torch works on floating point data types.
c = torch.tensor([[10,2,8,6,4],[10,2,8,6,4]], dtype=torch.float)
print("mean",torch.mean(c))
print("median",torch.median(c))
print("mode",torch.mode(c))
print("standard deviation",torch.std(c))

mean tensor(6.)
median tensor(6.)
mode torch.return_types.mode(
values=tensor([2., 2.]),
indices=tensor([1, 1]))
standard deviation tensor(2.9814)


In [14]:
# dot product of two tensors
# (m × n) @ (n × p) → (m × p)
first_tens = torch.tensor([[12,10,11], [13,15,14]])
second_tens = torch.tensor([[1,2], [5,6], [7,8]])

result = torch.matmul(first_tens,second_tens)
print(result)

tensor([[139, 172],
        [186, 228]])


In [15]:
# compute matrix product of 5 2d tensors
first = torch.randn(2,3)
second = torch.randn(3,4)
third = torch.randn(4,5)
torch.linalg.multi_dot((first, second, third))

tensor([[ 0.4560, -3.0964, -3.4617,  2.5408,  0.7445],
        [-6.8987,  3.3466,  0.8549, -2.4724,  2.0436]])

In [16]:
# compute eigen values and eigenvalues
A = torch.randn(4,4)

print("Matrix:", A)

eigenvalues, eigenvectors = torch.linalg.eig(A)

print("Eigen Values", eigenvalues)
print("Eigen Vectors", eigenvectors)


Matrix: tensor([[-0.9091,  1.1795, -1.6634,  0.9382],
        [-0.5124, -0.5750, -0.2024,  2.6459],
        [-0.1011, -0.0699,  0.1476, -1.1862],
        [-2.1680,  0.9506, -0.3166,  1.2234]])
Eigen Values tensor([-2.2477+0.0000j,  1.2691+1.5639j,  1.2691-1.5639j, -0.4036+0.0000j])
Eigen Vectors tensor([[-0.5156+0.0000j, -0.5757+0.0000j, -0.5757-0.0000j, -0.3772+0.0000j],
        [ 0.6307+0.0000j, -0.4272-0.3235j, -0.4272+0.3235j, -0.7550+0.0000j],
        [-0.2601+0.0000j,  0.3428+0.0441j,  0.3428-0.0441j, -0.5116+0.0000j],
        [-0.5185+0.0000j, -0.1917-0.4746j, -0.1917+0.4746j, -0.1611+0.0000j]])


## Import libraries and dataset

In [17]:
# Once the loss function is defined, we calculate its derivative with respect to the model parameters.
# Using this derivative, we iteratively adjust the parameters so the loss function approaches its minimum value.
# This process is known as iterative optimization, where an optimizer is used to perform these parameter updates.

x = torch.autograd.Variable(torch.Tensor([2]), requires_grad=True)
y = torch.autograd.Variable(torch.Tensor([1]), requires_grad=True)
z = torch.autograd.Variable(torch.Tensor([5]), requires_grad=True)

a = x - y
f = z * a
print("Final value for Function f = ", f) # loss function
f.backward()
print("Gradient value for x:", x.grad)  # tensor([5.])
print("Gradient value for y:", y.grad)  # tensor([-5.])
print("Gradient value for z:", z.grad)  # tensor([1.])




Final value for Function f =  tensor([5.], grad_fn=<MulBackward0>)
Gradient value for x: tensor([5.])
Gradient value for y: tensor([-5.])
Gradient value for z: tensor([1.])


In [18]:
import torch
from torchvision.datasets import CIFAR10
from keras.datasets import cifar10
from matplotlib import pyplot

3#train=True - This tells PyTorch you want the training set (50,000 images).
#If train=False, you’d get the test set (10,000 images).
#download=True - If the dataset isn’t found in the root directory,  download ## from the internet automatically.
train_data = CIFAR10(root="./train",
                     train=True,
                     download=True) # inside train folder data will be stored

ModuleNotFoundError: No module named 'torchvision'

## load dataset

In [ ]:
(trainX, trainy), (testX, testy) = cifar10.load_data()
print('Train: X=%s, y=%s' % (trainX.shape, trainy.shape))
print('Test: X=%s, y=%s' % (testX.shape, testy.shape))


## display image

In [ ]:
# Display images
# Plot the first sixteen images
for i in range(16):
    # Define subplot (4x4 grid)
    pyplot.subplot(4, 4, i + 1)
    # Plot raw pixel data
    pyplot.imshow(trainX[i])
# Show the figure
pyplot.show()


## Examine training dataset

In [ ]:
# Examine the training dataset
print(train_data.data.shape)
print(train_data.class_to_idx)


## check class labels

In [ ]:
# Check the class labels
for i in range(16):
    data, label = train_data[i]
    print("Picture: " + str(i+1) + ", photograph: ", train_data.classes[label])


## data tranforms

In [ ]:
from torchvision import transforms
from torchvision.datasets import CIFAR10
train_data_path = "./train/"
train_transforms = transforms.Compose([
    transforms.Resize(64), #resize 6864 resolution
    transforms.ToTensor(),
    transforms.Normalize(
        mean=(0.4914, 0.4822, 0.4465),
        std=(0.2023, 0.1994, 0.2010))
])
training_data = CIFAR10(train_data_path,
                        train=True,
                        download=True,
                        transform=train_transforms)


## Training data of first image

In [ ]:
# Training data of first image
print(training_data[0])


## Defining transform for testing data set

In [ ]:
test_data_path = "./test/"
test_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        (0.4914, 0.4822, 0.4465),
        (0.2023, 0.1994, 0.2010))
])
test_data = CIFAR10(
    test_data_path,
    train=False,
    download=True,
    transform=train_transforms
)


100%|██████████| 170M/170M [00:04<00:00, 36.7MB/s]


## data batching

In [ ]:
from torch.utils.data import DataLoader

batch_size = 16

training_data_loader = DataLoader(training_data, batch_size=batch_size, shuffle=True)
test_data_loader = DataLoader(test_data, batch_size=batch_size, shuffle=False)

## Model development and training

### Import libraries

In [ ]:
# Import libraries and dataset
from torchvision import models
from torch import optim
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F


## Define neural network

In [ ]:
# Define neural network, __init__ and forward functions
class Net(nn.Module):                          # Define a custom neural network by extending nn.Module
    def __init__(self):                        # Constructor: define all layers here
        super(Net, self).__init__()            # Call the parent constructor (nn.Module)

        # First convolution layer: input has 3 channels (RGB), output has 6 feature maps, kernel size = 5x5
        self.conv1 = nn.Conv2d(3, 6, 5)

        # Max pooling layer: 2x2 filter, stride=2 (reduces width and height by half each time)
        self.pool = nn.MaxPool2d(2, 2)

        # Second convolution layer: input has 6 channels, output has 16 feature maps, kernel size = 5x5
        self.conv2 = nn.Conv2d(6, 16, 5)

        # First fully connected layer (dense): input features = 16*5*5, output = 120 neurons
        #nn.Linear(in_features, out_features) - in_features is number of inputs each neuron in this layer receives
        #out_features = the number of neurons in that layer (the outputs)
        self.fc1 = nn.Linear(16*5*5, 120)

        # Second fully connected layer: input = 120 neurons, output = 84 neurons
        self.fc2 = nn.Linear(120, 84)

        # Final fully connected layer: input = 84 neurons, output = 10 (for CIFAR-10 classes)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):                      # Forward pass: defines how input flows through the network
        # Apply first convolution -> ReLU activation -> Max pooling
        x = self.pool(F.relu(self.conv1(x)))

        # Apply second convolution -> ReLU activation -> Max pooling
        x = self.pool(F.relu(self.conv2(x)))

        # Flatten the 3D feature maps into a 1D vector for fully connected layers
        x = x.view(-1, 16 * 5 * 5)

        # Pass through first fully connected layer with ReLU
        x = F.relu(self.fc1(x)) # with relu all neagtive value set to zero and postive value left unchanged

        # Pass through second fully connected layer with ReLU
        x = F.relu(self.fc2(x))

        # Pass through final fully connected layer (no activation, raw class scores / logits)
        x = self.fc3(x)

        return x                               # Output: logits for 10 classes


## Instantiate the Model

In [ ]:
# Instantiate the model
net = Net()

# Define the loss function (CrossEntropyLoss is common for classification)
criterion = nn.CrossEntropyLoss()

# Define the optimizer (Stochastic Gradient Descent with momentum)
# lr=0.001 → how big each step is
# momentum=0.9 → how much of the previous velocity is kept
# 0.9 means 90% of the previous update is carried forward.
# This is a typical default in many models.
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9) # With momentum, the optimizer builds up speed in consistent directions

## Load and transform data

In [ ]:
import torchvision
# Define transformations: convert to tensor + normalize RGB channels
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        mean=(0.5, 0.5, 0.5),   # normalize each channel (R,G,B)
        std=(0.5, 0.5, 0.5)
    )
])

# Training dataset + dataloader
trainset = torchvision.datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

trainloader = torch.utils.data.DataLoader(
    trainset,
    batch_size=4,
    shuffle=True,
    num_workers=2
)

# Test dataset + dataloader
testset = torchvision.datasets.CIFAR10(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

testloader = torch.utils.data.DataLoader(
    testset,
    batch_size=4,
    shuffle=False,
    num_workers=2
)

100%|██████████| 170M/170M [00:02<00:00, 73.3MB/s]


## Train the network

In [ ]:
# Train the Network

num_epochs = 10  # number of times to loop through the dataset

for epoch in range(num_epochs):
    running_loss = 0.0 #keeps track of the cumulative loss during the epoch

    for i, data in enumerate(trainloader, 0): #batch_idx -label for 1st batch is 0 #inputs.shape = [4, 3, 32, 32]  -4 images in the batch and labels of those images
        inputs, labels = data
        optimizer.zero_grad() #Clears old gradients from the previous step

        # Forward pass
        outputs = net(inputs) #Passes the batch of images through your neural network. #outputs.shape = [4, 10]
        loss = criterion(outputs, labels)
        #criterion is your loss function (nn.CrossEntropyLoss).# It compares:# outputs (predicted class scores)# labels (true class indices)

        # Backward pass + optimize
        loss.backward() #computes the gradients of the loss w.r.t. every trainable parameter (weights & biases) using backpropagation
        optimizer.step() #Updates the network parameters using the computed gradients, optimizer takes each parameter (weight, bias) and adjusts it slightly in the direction that reduces the loss
        # Accumulate loss
        running_loss += loss.item() # training loss since we are iterating training loader

        # Print statistics every 2000 mini-batches
        if i % 2000 == 1999:  # print every 2000 mini-batches
            print(f"[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}")
            running_loss = 0.0

print("Finished Training ")
